stages:
  - build
  - test
  - prodmigrations
  - devmigrations
  - testmigrations
  - deploy
  - documentation
  - sonar

variables:
  IMAGE_NAME: roombooking:latest
  CONTAINER_NAME: roombooking-container
  DOCKER_HOST: unix:///var/run/docker.sock
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  FLYWAY_VERSION: 12.3.0

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore

    - cd RoomBooking/

    - dotnet publish --configuration Release --output ./publish --no-build

    - cd ../
  artifacts:
    paths:
      - RoomBooking.Tests/bin/Release
      - RoomBooking/publish
    expire_in: 2 hour
  only:
    - master

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0
  before_script:
    - if [ -z "$DP_LIB_PASSWORD" ]; then echo "DP_LIB_PASSWORD is not set"; exit 1; fi
  script:
    - dotnet test RoomBooking.Tests/bin/Release/net10.0/RoomBooking.Tests.dll --no-build
  dependencies:
    - build
  only:
    - master


prodmigrations:
  stage: prodmigrations
  image: 
    name: flyway/flyway:${FLYWAY_VERSION}
    entrypoint: [""]
  script:
      - flyway -url="jdbc:postgresql://localhost:5432/RoomBooking" -user="Booker" -password="$DP_LIB_PASSWORD" -schemas="prod" -table="prod_schema_history" -locations="filesystem:./Migrations/Prod" -validateMigrationNaming=true migrate
  dependencies: []
  only:
    - master

devmigrations:
  stage: devmigrations
  image: 
    name: flyway/flyway:${FLYWAY_VERSION}
    entrypoint: [""]
  script:
      - flyway -url="jdbc:postgresql://localhost:5432/RoomBooking" -user="Booker" -password="$DP_LIB_PASSWORD" -schemas="dev" -table="dev_schema_history" -locations="filesystem:./Migrations/Dev" -validateMigrationNaming=true migrate
  dependencies: []
  only:
    - Dev

testmigrations:
  stage: testmigrations
  image: 
    name: flyway/flyway:${FLYWAY_VERSION}
    entrypoint: [""]
  script:
      - flyway -url="jdbc:postgresql://localhost:5432/RoomBooking" -user="Booker" -password="$DP_LIB_PASSWORD" -schemas="test" -table="test_schema_history" -locations="filesystem:./Migrations/Test" -validateMigrationNaming=true migrate
  dependencies: []
  only:
    - Test

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - docker version
    - docker info
  script:
    - cd RoomBooking/

    - docker-compose build

    - docker-compose down --remove-orphans || true

    - docker network prune -f

    - export DP_LIB_PASSWORD=$DP_LIB_PASSWORD

    - docker-compose up -d

    - docker system prune -f
  dependencies:
    - build
  only:
    - master

documentation:
  stage: documentation
  image: docker:latest
  before_script:
    - docker version
    - docker info
    - apk add dotnet10-sdk
    - dotnet --version
  script:
    - dotnet tool restore

    - dotnet docfx RoomBooking/docfx.json
    
    - mv RoomBooking/_site/ DocfxContainer/_site

    - cd ./DocfxContainer

    - docker-compose build
    
    - docker-compose down --remove-orphans || true

    - docker network prune -f

    - docker-compose up -d

    - docker system prune -f
  artifacts:
    paths:
      - DocfxContainer/_site
    expire_in: 2 hour
  only:
    - tags

sonar:
  stage: sonar
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    -  dotnet tool restore
    -  dotnet dotnet-sonarscanner begin /k:\"RoomBooking\" /d:sonar.token=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_HOST_URL\"
    -  dotnet build
    -  dotnet dotnet-sonarscanner end /d:sonar.token=\"$SONAR_TOKEN\"
  cache:
    policy: pull-push
    key: sonar-cache-$CI_COMMIT_REF_SLUG
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner
  dependencies: []
  when: manual
  allow_failure: true
  only:
    - master