stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: roombooking:latest
  CONTAINER_NAME: roombooking-container
  DOCKER_HOST: unix:///var/run/docker.sock

# Кэширование папок с зависимостями для ускорения сборки
cache:
  paths:
    - ~/.nuget/packages/

# Этап сборки
build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore
    - dotnet publish --configuration Release --output ./publish --no-build
  artifacts:
    paths:
      - ./publish
    expire_in: 2 hour
  only:
    - master

# Этап тестирования (опционально)
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  before_script:
    - if [ -z "$DP_LIB_PASSWORD" ]; then echo "DP_LIB_PASSWORD is not set"; exit 1; fi
  script:
    - dotnet test --configuration Release --no-build --verbosity normal
  dependencies:
    - build
  only:
    - master

# Этап деплоя
deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - docker version
    - docker info
  script:
    # Сборка через docker-compose
    - docker-compose build
    
    # Остановка старых контейнеров
    - docker-compose down --remove-orphans || true

    #Очитска весящих сетей
    - docker network prune -f

    # Получение пароля от дб из гитлаба
    - export DP_LIB_PASSWORD=$DP_LIB_PASSWORD

    # Запуск новых контейнеров
    - docker-compose up -d

    # Очистка
    - docker system prune -f
  only:
    - master