stages:
  - build
  - test
  - deploy
  - documentation

variables:
  IMAGE_NAME: roombooking:latest
  CONTAINER_NAME: roombooking-container
  DOCKER_HOST: unix:///var/run/docker.sock

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore

    - cd RoomBooking/

    - dotnet publish --configuration Release --output ./publish --no-build
  artifacts:
    paths:
      - RoomBooking/bin
      - RoomBooking/obj
      - RoomBooking/publish

      - RoomBooking.Tests/bin
      - RoomBooking.Tests/obj
    expire_in: 2 hour
  only:
    - master

# Этап тестирования
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0
  before_script:
    - if [ -z "$DP_LIB_PASSWORD" ]; then echo "DP_LIB_PASSWORD is not set"; exit 1; fi
  script:
    - dotnet test RoomBooking.Tests/RoomBooking.Tests.csproj --configuration Release --no-build --verbosity normal
  only:
    - master

# Этап деплоя
deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - docker version
    - docker info
  script:
    - cd RoomBooking/

    # Сборка через docker-compose
    - docker-compose build
    
    # Остановка старых контейнеров
    - docker-compose down --remove-orphans || true

    #Очитска весящих сетей
    - docker network prune -f

    # Получение пароля от дб из гитлаба
    - export DP_LIB_PASSWORD=$DP_LIB_PASSWORD

    # Запуск новых контейнеров
    - docker-compose up -d

    # Очистка
    - docker system prune -f
  only:
    - master

pages:
  stage: documentation
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - dotnet tool restore

    - dotnet docfx RoomBooking/docfx.json
    
    - mv RoomBooking/_site/ ./public
  artifacts:
    paths:
      - public
    expire_in: 2 hour
  only:
    - tags