services:
  web:
    image: ${IMAGE_NAME:-roombooking:latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-roombooking-container}
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production
      - DP_LIB_PASSWORD=${DP_LIB_PASSWORD}